spring:
  application:
    name: models
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: true
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=themajorones
    username: sa
    password: YourPassword123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

logging:
  level:
    root: INFO
